Console.WriteLine("");
Console.WriteLine("Ingrese el tipo de atención: ");
Console.WriteLine("");
Console.WriteLine("- 1. Emergencia");
Console.WriteLine("- 2. Consulta");
Console.WriteLine("- 3. Pediatría");
Console.WriteLine("- 4. Traumatología");
Console.WriteLine("");
int atencion=int.Parse(Console.ReadLine());
Console.WriteLine("");
Console.WriteLine("Ingrese la edad del paciente: ");
Console.WriteLine("");
int edad=int.Parse(Console.ReadLine());
Console.WriteLine("");
Console.WriteLine("Ingrese la temperatura del paciente: ");
Console.WriteLine("");
double temperatura = double.Parse(Console.ReadLine());
Console.WriteLine("");
Console.WriteLine("Ingrese la saturación de oxígeno del paciente: ");
Console.WriteLine("");
double saturacion = double.Parse(Console.ReadLine());
Console.WriteLine("");
Console.WriteLine("Ingrese el nivel de dolor del paciente (1-10): ");
Console.WriteLine("");
int dolor = int.Parse(Console.ReadLine());
Console.WriteLine("");
Console.WriteLine("Ingrese la presión sistólica del paciente: ");
Console.WriteLine("");
int presion = int.Parse(Console.ReadLine());
Console.WriteLine("");